[package]
name = "inputplug"
version = "0.4.0"
authors = ["Andrej Shadura <andrew@shadura.me>"]
edition = "2018"
description = "XInput monitor daemon"
license = "MIT"
repository = "https://github.com/andrewshadura/inputplug"

[dependencies]
structopt = { version = "0.3", default-features = false }
nix = "0.19"
anyhow = "1.0"

[dependencies.pidfile-rs]
optional = true

[features]
default = ["pidfile"]
pidfile = ["pidfile-rs"]

[dependencies.x11rb]
version = "0.8"
features = ["xinput"]
